# Previous instructions for ElasticSearch
# sysctl -w vm.max_map_count=262144
# echo 'vm.max_map_count=262144' >> /etc/sysctl.conf

version: "3.7"
services:
  # victim:
  #   container_name: victim
  #   image: httpd:alpine
  #   ports: 
  #     - 8080:80
  #   networks:
  #     - tfm
    
  # kali:
  #   container_name: kali
  #   build: ./kali
  #   networks:
  #     - tfm

  suricata:
    build:
      context: ./suricata
      dockerfile: Dockerfile
    container_name: suricata
    restart: always
    environment:
     - OINKCODE
     - KAFKA_BROKER=broker:9092
     - KAFKA_TOPIC=numtest
     - KAFKA_GROUP_ID=my-group
     - INTERFACE=wlan0
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    volumes:
     - ./data/suricata/log:/var/log/suricata

  filebeat:
    build:
      context: ./filebeat
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: filebeat
    environment:
      - KIBANA_URL=kibana:5601
      - ELASTICSEARCH_URL=elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=secure
      - KAFKA_BROKER=broker:9092
      - strict.perms=false
    volumes:
      - ./data/suricata/log:/var/log/suricata
    networks:
      - tfm
      
networks:
  tfm:
    driver: bridge
