# Previous instructions for ElasticSearch
# sysctl -w vm.max_map_count=262144
# echo 'vm.max_map_count=262144' >> /etc/sysctl.conf

version: "3.7"
services:
  
  suricata:
    build:
      context: ./suricata
      dockerfile: Dockerfile
    container_name: suricata
    restart: always
    environment:
     - OINKCODE
     - KAFKA_BROKER=192.168.1.53:9092
     - KAFKA_TOPIC=$KAFKA_TOPIC
     - KAFKA_GROUP_ID=$KAFKA_GROUP_ID
     - INTERFACE=$INTERFACE
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    volumes:
     - ./data/suricata/log:/var/log/suricata

  filebeat:
    build:
      context: ./filebeat
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: filebeat
    environment:
      - KIBANA_URL=192.168.1.53:5601
      - ELASTICSEARCH_URL=192.168.1.53:9200
      - ELASTICSEARCH_USERNAME=$ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD=$ELASTICSEARCH_PASSWORD
      - strict.perms=false
    volumes:
      - ./data/suricata/log:/var/log/suricata
    networks:
      - edge

  filebeat2:
    build:
      context: ./filebeat2
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: filebeat2
    environment:
      - KAFKA_BROKER=192.168.1.53:29092
      - strict.perms=false
    volumes:
      - ./data/suricata/log:/var/log/suricata
    networks:
      - edge

  # victim:
  #   container_name: victim
  #   image: httpd:alpine
  #   ports: 
  #     - 8080:80
  #   networks:
  #     - edge
    
  # kali:
  #   container_name: kali
  #   build: ./kali
  #   networks:
  #     - edge
      
networks:
  edge:
    driver: bridge
