# filebeat.config:
#   modules:
#     path: ${path.config}/modules.d/*.yml
#     reload.enabled: false

filebeat.inputs:
  - type: log
    paths:
      - /var/log/suricata/eve.json
    json.keys_under_root: true
    # json.add_error_key: true
    # json.message_key: log

# filebeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true

# processors:
# - add_cloud_metadata: ~

# output.console:
#   pretty: true

output.kafka:
  hosts: ["broker:29092"]
  topic: 'suricata-%{[event_type]}'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

# output.elasticsearch:
#   hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#   username: '${ELASTICSEARCH_USERNAME:}'
#   password: '${ELASTICSEARCH_PASSWORD:}'

# setup.kibana:
#   host: "kibana:5601"

# setup.dashboards.enabled: true