filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: log
    paths:
      - /var/log/suricata/eve.json
    json.keys_under_root: true
    # json.add_error_key: true
    # json.message_key: log

# output.console:
#   pretty: true

output.elasticsearch:
  hosts: "${ELASTICSEARCH_URL:elasticsearch:9200}"
  username: "${ELASTICSEARCH_USERNAME:}"
  password: "${ELASTICSEARCH_PASSWORD:}"

setup.kibana:
  host: "${KIBANA_URL:kibana:5601}"

setup.dashboards.enabled: true